---
Name: silverstripe-theme-picker
---

# Configure Admin Extensions:

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - AndrewAndante\ThemePicker\SiteConfigExtension
PageController:
  extensions:
    - AndrewAndante\ThemePicker\PageControllerExtension
